@@ -8,6 +8,19 @@ services:
       - ALLOW_EMPTY_PASSWORD=yes
     volumes:
       - 'mariadb_data:/bitnami'
+  redis:
+    image: 'docker.io/bitnami/redis:6.0-debian-10'
+    environment:
+      - ALLOW_EMPTY_PASSWORD=yes
+      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
+    ports:
+      - '6379:6379'
+    volumes:
+      - 'redis_data:/bitnami/redis/data'
+  memcached:
+    image: 'docker.io/bitnami/memcached:1-debian-10'
+    ports:
+      - '11211:11211'
   joomla:
     image: 'docker.io/bitnami/joomla:3-debian-10'
     environment:
@@ -23,8 +36,13 @@ services:
       - 'joomla_data:/bitnami'
     depends_on:
       - mariadb
+      - redis
+      - memcached
+
 volumes:
   mariadb_data:
     driver: local
   joomla_data:
     driver: local
+  redis_data:
+    driver: local
